// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIt67ekB3cbPgzALeieZrcOkD62Aa89XA',
    appId: '1:971325451831:web:4e02a057302d8c93c819b2',
    messagingSenderId: '971325451831',
    projectId: 'fir-first-app-13bbd',
    authDomain: 'fir-first-app-13bbd.firebaseapp.com',
    storageBucket: 'fir-first-app-13bbd.appspot.com',
    measurementId: 'G-D94MTK9DHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTF-RqCC-yiKv9WaHT3GbdcRYvq5gAguk',
    appId: '1:971325451831:android:838b7c9ccce28186c819b2',
    messagingSenderId: '971325451831',
    projectId: 'fir-first-app-13bbd',
    storageBucket: 'fir-first-app-13bbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW67MGfBWMBDJmUat83c35L3Lh9SX9cdc',
    appId: '1:971325451831:ios:ea75941cb3461d41c819b2',
    messagingSenderId: '971325451831',
    projectId: 'fir-first-app-13bbd',
    storageBucket: 'fir-first-app-13bbd.appspot.com',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW67MGfBWMBDJmUat83c35L3Lh9SX9cdc',
    appId: '1:971325451831:ios:ea75941cb3461d41c819b2',
    messagingSenderId: '971325451831',
    projectId: 'fir-first-app-13bbd',
    storageBucket: 'fir-first-app-13bbd.appspot.com',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIt67ekB3cbPgzALeieZrcOkD62Aa89XA',
    appId: '1:971325451831:web:cfaf7793aa5d7f8cc819b2',
    messagingSenderId: '971325451831',
    projectId: 'fir-first-app-13bbd',
    authDomain: 'fir-first-app-13bbd.firebaseapp.com',
    storageBucket: 'fir-first-app-13bbd.appspot.com',
    measurementId: 'G-Z3960GLWSX',
  );
}
